project/plugins.sbt
=> DLS-SCALASTYLE ScalaCodeStyle plugin added

test/uk/gov/helptosavereminder/controllers/EmailCallbackControllerSpec.scala
Added additional test coverage
=> DLS-1452-Test

app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, project/AppDependencies.scala, test/uk/gov/helptosavereminder/controllers/EmailCallbackControllerSpec.scala, test/uk/gov/helptosavereminder/repo/HtsReminderRepositorySpec.scala
=> DLS-1790 Unit Test Coverage and configuring mongoDB-

app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, conf/application.conf
=> DLS-1854 Changes as per YAML file

conf/application.conf
Application router path changed
=> DLS-Change-Router-To-Application  Application router path changed

app/uk/gov/hmrc/helptosavereminder/controllers/ReminderGeneratorController.scala, conf/app.routes, conf/application.conf
Bootstrap to be added as controller
=> DLS-BOOTSTRAP-CONTROLLER Bootstrap to be added as controller

app/uk/gov/hmrc/helptosavereminder/actors/HtsUserUpdateActor.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala
=> DLS-ADD-ERROR-MESSAGES Error tracing messages added

app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/HtsUserUpdateActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, app/uk/gov/hmrc/helptosavereminder/auth/HtsReminderAuth.scala, app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/ReminderGeneratorController.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, app/uk/gov/hmrc/helptosavereminder/models/test/ReminderGenerator.scala, app/uk/gov/hmrc/helptosavereminder/modules/ReminderJobModule.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, conf/app.routes, project/AppDependencies.scala, test/uk/gov/helptosavereminder/actors/EmailSenderActorSpec.scala, test/uk/gov/helptosavereminder/actors/ProcessingSupervisorSpec.scala, test/uk/gov/helptosavereminder/repo/HtsReminderRepositorySpec.scala
HTS user update connector added
=> DLS-1867 HTS user update connector added

app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/HtsUserUpdateActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, app/uk/gov/hmrc/helptosavereminder/auth/HtsReminderAuth.scala, app/uk/gov/hmrc/helptosavereminder/config/Scheduler.scala, app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, app/uk/gov/hmrc/helptosavereminder/util/package.scala, conf/application.conf, project/AppDependencies.scala, test/uk/gov/helptosavereminder/controllers/EmailCallbackControllerSpec.scala
DLS-Create-Scheduler scheduler stubs added
=> DLS-Create-Scheduler

conf/app.routes
DLS-Create-Scheduler --  changes for URL
=> DLS-Create-Scheduler --  changes for URL

app/uk/gov/hmrc/helptosavereminder/auth/HtsReminderAuth.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/ReminderGeneratorController.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, conf/app.routes, project/AppDependencies.scala, test/uk/gov/helptosavereminder/actors/EmailSenderActorSpec.scala, test/uk/gov/helptosavereminder/controllers/AuthSupport.scala, test/uk/gov/helptosavereminder/controllers/EmailCallbackControllerSpec.scala, test/uk/gov/helptosavereminder/controllers/HelpToSaveAuthSpec.scala, test/uk/gov/helptosavereminder/controllers/ReminderControllerSpec.scala, test/uk/gov/helptosavereminder/repo/HtsReminderRepositorySpec.scala, test/uk/gov/helptosavereminder/utils/TestData.scala, test/uk/gov/helptosavereminder/utils/TestSupport.scala
DLS-1984 CancelHtsReminder for the user implemented together with Test coverage
=> DLS-1984 CancelHtsReminder for the user implemented together with Test coverage

app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, app/uk/gov/hmrc/helptosavereminder/util/DateTimeFunctions.scala, conf/app.routes, test/uk/gov/helptosavereminder/controllers/ReminderControllerSpec.scala, test/uk/gov/helptosavereminder/repo/HtsReminderRepositorySpec.scala, test/uk/gov/helptosavereminder/utils/DateTimeFunctionsSpec.scala
DLS-1971 Date changes added too
=> DLS-1971 Date changes added too

app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/HtsUserUpdateActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, app/uk/gov/hmrc/helptosavereminder/util/DateTimeFunctions.scala, conf/app.routes, conf/application.conf, test/uk/gov/helptosavereminder/actors/EmailSenderActorSpec.scala, test/uk/gov/helptosavereminder/controllers/ReminderControllerSpec.scala, test/uk/gov/helptosavereminder/repo/HtsReminderRepositorySpec.scala, test/uk/gov/helptosavereminder/utils/DateTimeFunctionsSpec.scala
=> DLS-1971 Schedulers added

app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, app/uk/gov/hmrc/helptosavereminder/models/test/ReminderGenerator.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, test/uk/gov/helptosavereminder/controllers/ReminderControllerSpec.scala, test/uk/gov/helptosavereminder/repo/HtsReminderRepositorySpec.scala, test/uk/gov/helptosavereminder/utils/DateTimeFunctionsSpec.scala
DLS-2042 NextSendDate update correctly when user account created
=> DLS-2042 NextSendDate update correctly when user account created

app/uk/gov/hmrc/helptosavereminder/controllers/ReminderGeneratorController.scala, conf/app.routes
DLS-GenerateController -- Generate reminders is back
=> DLS-GenerateController -- Generate reminders is back

app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, app/uk/gov/hmrc/helptosavereminder/util/DateTimeFunctions.scala, conf/application.conf
DLS-Remove-Multiple-Reschedules  remove multiple reschedules
=> DLS-Remove-Multiple-Reschedules  remove multiple reschedules

app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/audit/HTSAuditor.scala, app/uk/gov/hmrc/helptosavereminder/config/AppConfig.scala, app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/models/HTSEvent.scala, conf/application.conf, test/uk/gov/helptosavereminder/controllers/ReminderControllerSpec.scala, test/uk/gov/helptosavereminder/utils/TestSupport.scala
DLA-1948 Auditing events handled
=> DLS-1948 Auditing events handled

app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, conf/app.routes, conf/application.conf, test/uk/gov/helptosavereminder/controllers/ReminderControllerSpec.scala
DLS-Naming-Convention DLS-Naming convention changed
=> DLS-Naming-Convention DLS-Naming convention changed

app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, conf/app.routes, conf/application.conf, test/uk/gov/helptosavereminder/controllers/EmailCallbackControllerSpec.scala
Email calback controller functionality
=> DLS-2146 Email calback controller functionality

app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, app/uk/gov/hmrc/helptosavereminder/models/test/ReminderGenerator.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, build.sbt, conf/application.conf, test/uk/gov/helptosavereminder/controllers/EmailCallbackControllerSpec.scala, test/uk/gov/helptosavereminder/repo/HtsReminderRepositorySpec.scala
=> DLS-BounceCount Bouncecount is removed

app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/util/DateTimeFunctions.scala, conf/application.conf, test/uk/gov/helptosavereminder/utils/DateTimeFunctionsSpec.scala
DLS-DynamicMonth Dynamic month code added
=> DLS-DynamicMonth Dynamic month code added

app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, app/uk/gov/hmrc/helptosavereminder/util/DateTimeFunctions.scala, conf/application.conf
First commit DLS-SummerTimeAdjustment
=> First commit DLS-SummerTimeAdjustment

app/uk/gov/hmrc/helptosavereminder/util/DateTimeFunctions.scala, conf/application.conf
=> DLS-BSTAdjustments BST Time adjustments

app/uk/gov/hmrc/helptosavereminder/util/DateTimeFunctions.scala
=> DLS-BSTAdjustment BST adjustment code done

app/uk/gov/hmrc/helptosavereminder/util/DateTimeFunctions.scala
DLS-LondonTime London time zone changed
=> DLS-LondonTime London time zone changed

app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/models/EmailConnectors.scala, conf/application.conf
DLS-EmailActor For callBack from Email Service
=> DLS-EmailActor 

app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, conf/application.conf, project/AppDependencies.scala
=> DLS-tempCronSchedule

conf/application.conf
=> DLS- Test for time change

app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala
=> DLS-ConfigTest1

README.md, app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/HtsUserUpdateActor.scala, app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, app/uk/gov/hmrc/helptosavereminder/models/test/ReminderGenerator.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, conf/application.conf, project/AppDependencies.scala, test/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActorSpec.scala, test/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisorSpec.scala, test/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackControllerSpec.scala, test/uk/gov/hmrc/helptosavereminder/controllers/ReminderControllerSpec.scala, test/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepositorySpec.scala
Fix for missing daysToReceive empty value
=> DLS-IntTestFix

app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala
repoLockPeriod is printed for debugging
=> DLS-RepoLockPeriodTest

app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala
=> DLS-WithoutRepoLock 

app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala
DLS-RevertRepoLockPeriod Locking Repo logic brought back
=> DLS-RevertRepoLockPeriod 

app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala
Mapping is changed for Future fetch
=> DLS-RepoFutureFetch 

app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, test/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisorSpec.scala
Testing with a Single User Schedule
=> DLS-ProcessSingleRecord

build.sbt, conf/application.conf, test/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActorSpec.scala, test/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisorSpec.scala
=> DLS-ProcessSingleRecord 

app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, build.sbt, conf/application.conf, test/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActorSpec.scala, test/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisorSpec.scala
Reverting all changes done on 09092020
=> DLS-revert08092020

app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, conf/application.conf
Bringing the callBackrefUrl back
=> DLS-CallbackUrlRefIndex 

app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, test/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepositorySpec.scala
Reverts hmrc/help-to-save-reminder#67
=> Revert "DLS-1946 Deletion errors updated"

app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, build.sbt, test/uk/gov/hmrc/helptosavereminder/controllers/ReminderControllerSpec.scala
Reverts hmrc/help-to-save-reminder#69
=> Revert "DLS-3614: Implementing forbidden error code for incorrect user credentials  "

app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, app/uk/gov/hmrc/helptosavereminder/audit/HTSAuditor.scala, app/uk/gov/hmrc/helptosavereminder/auth/HtsReminderAuth.scala, app/uk/gov/hmrc/helptosavereminder/config/AppConfig.scala, app/uk/gov/hmrc/helptosavereminder/connectors/EmailConnector.scala, app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/test/TestController.scala, project/AppDependencies.scala, test/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActorSpec.scala, test/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisorSpec.scala, test/uk/gov/hmrc/helptosavereminder/connectors/EmailConnectorSpec.scala, test/uk/gov/hmrc/helptosavereminder/controllers/AuthSupport.scala, test/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackControllerSpec.scala, test/uk/gov/hmrc/helptosavereminder/controllers/HelpToSaveAuthSpec.scala, test/uk/gov/hmrc/helptosavereminder/controllers/ReminderControllerSpec.scala, test/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepositorySpec.scala, test/uk/gov/hmrc/helptosavereminder/utils/DateTimeFunctionsSpec.scala, test/uk/gov/hmrc/helptosavereminder/utils/TestData.scala, test/uk/gov/hmrc/helptosavereminder/utils/TestSupport.scala
The only remaining warnings in HTSR are warnings over auth credentials. We're opting to resolve these at a later date (PRA permitting)
=> DLS-3725: Reducing number of compilation warnings

app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala
This is to stop emails form being sent out after the nextSendDate has been updated
=> DLS-3465 Added Param check to Mongo Query

app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/HtsUserUpdateActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, app/uk/gov/hmrc/helptosavereminder/audit/HTSAuditor.scala, app/uk/gov/hmrc/helptosavereminder/auth/HtsReminderAuth.scala, app/uk/gov/hmrc/helptosavereminder/config/Scheduler.scala, app/uk/gov/hmrc/helptosavereminder/connectors/EmailConnector.scala, app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, build.sbt, conf/application.conf, project/AppDependencies.scala, project/build.properties, project/plugins.sbt
=> Dave/dls 3878/play 27

app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/HtsUserUpdateActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, app/uk/gov/hmrc/helptosavereminder/audit/HTSAuditor.scala, app/uk/gov/hmrc/helptosavereminder/auth/HtsReminderAuth.scala, app/uk/gov/hmrc/helptosavereminder/config/AppConfig.scala, app/uk/gov/hmrc/helptosavereminder/config/Scheduler.scala, app/uk/gov/hmrc/helptosavereminder/connectors/EmailConnector.scala, app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/test/TestController.scala, app/uk/gov/hmrc/helptosavereminder/models/Email.scala, app/uk/gov/hmrc/helptosavereminder/models/HTSEvent.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, app/uk/gov/hmrc/helptosavereminder/services/test/TestService.scala, build.sbt, conf/application.conf, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActorSpec.scala, test/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisorSpec.scala, test/uk/gov/hmrc/helptosavereminder/connectors/EmailConnectorSpec.scala, test/uk/gov/hmrc/helptosavereminder/controllers/AuthSupport.scala, test/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackControllerSpec.scala, test/uk/gov/hmrc/helptosavereminder/controllers/ReminderControllerSpec.scala, test/uk/gov/hmrc/helptosavereminder/utils/DateTimeFunctionsSpec.scala, test/uk/gov/hmrc/helptosavereminder/utils/TestSupport.scala
=> DLS-4132 Library Upgrades post Play28

build.sbt
Fix for failed build for scala doc error
=>  DLS-FixFailedBuildScalaDoc Fix for failed build for scala doc error

app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/HtsUserUpdateActor.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, app/uk/gov/hmrc/helptosavereminder/models/test/ReminderGenerator.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, test/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActorSpec.scala
Revert back to v0.110.0 and then reimplement endDate field
=> Dave/dls 4640/reminder end date

app/uk/gov/hmrc/helptosavereminder/controllers/EmailCallbackController.scala
Refactors the ugliest function in the program. To be squashed. Preserved step-by-step refactor history for review purposes.
=> DLS-8714 Refactor HtsReminderRepository

app/uk/gov/hmrc/helptosavereminder/actors/EmailSenderActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/HtsUserUpdateActor.scala, app/uk/gov/hmrc/helptosavereminder/actors/ProcessingSupervisor.scala, app/uk/gov/hmrc/helptosavereminder/audit/HTSAuditor.scala, app/uk/gov/hmrc/helptosavereminder/auth/HtsReminderAuth.scala, app/uk/gov/hmrc/helptosavereminder/connectors/EmailConnector.scala, app/uk/gov/hmrc/helptosavereminder/controllers/HtsUserUpdateController.scala, app/uk/gov/hmrc/helptosavereminder/controllers/test/TestController.scala, app/uk/gov/hmrc/helptosavereminder/models/Reminder.scala, app/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepository.scala, app/uk/gov/hmrc/helptosavereminder/util/JsErrorOps.scala, app/uk/gov/hmrc/helptosavereminder/util/package.scala, test/uk/gov/hmrc/helptosavereminder/controllers/AuthSupport.scala, test/uk/gov/hmrc/helptosavereminder/controllers/HelpToSaveAuthSpec.scala, test/uk/gov/hmrc/helptosavereminder/repo/HtsReminderRepositorySpec.scala
Simplified in the same vein as: https://github.com/hmrc/help-to-save/pull/264
Recommended reviewing commit-by-commit (there are only 8), since some of the changes are automated.
=> DLS-8714 Refactors to improve debugging experience
